N_TRIALS: 1
N_UPDATES:
  - 150 # Min value
  - 500 # Max value
N_EPOCHS:
  - 8 
  - 32
MINIBATCH_SIZE: [4, 6, 8, 12, 16, 24, 32, 40]
BATCHSIZE_MULTIPLIER:
  - 2
  - 12
LR:
  - 0.00005
  - 0.02
GAMMA:
  - 0.95
  - 0.999
GAE_LAMBDA:
  - 0.90
  - 0.999
ENT_COEF:
  - 0.0
  - 0.001
V_COEF:
  - 0.25
  - 0.75
GRADIENT_CLIP:
  - 0.005
  - 0.9
CLIP_VALUE_LOSS: True
CLIP_VALUE_COEF:
  - 0.1
  - 0.3
CLIP_RATIO:
  - 0.1
  - 0.3