N_TRIALS: 1
N_UPDATES:
  - 250 # Min value
  - 1000 # Max value
N_EPOCHS:
  - 8 
  - 25
MINIBATCH_SIZE: [10, 16, 24, 32, 48, 64, 96, 128]
BATCHSIZE_MULTIPLIER:
  - 2
  - 12
LR:
  - 0.00005
  - 0.02
N_SHOTS: 
  - 1
  - 1000
SAMPLE_PAULIS:
  - 100
  - 1000
GAMMA:
  - 0.95
  - 0.999
GAE_LAMBDA:
  - 0.90
  - 0.999
ENT_COEF:
  - 0.00005
  - 0.001
V_COEF:
  - 0.25
  - 0.75
GRADIENT_CLIP:
  - 0.005
  - 0.9
CLIP_VALUE_LOSS: True
CLIP_VALUE_COEF:
  - 0.1
  - 0.3
CLIP_RATIO:
  - 0.1
  - 0.3