n_epochs: [400, 2000]
batchsize: [50, 500]
opti_choice: ["Adam", "SGD"]
eta: [1e-5, 5e-2]
eta_2:
  values: [1e-4, 1e-1]
  conditional:
    use_eta_2: [0, 1]
epsilon: [0.005, 0.5]
grad_clip: [0.005, 1]
critic_loss_coeff: [0.1, 2]
sigma_eps: [1e-5, 1e-2]